#!/usr/bin/env bash
# session-start.sh — Front-loads harness anchor context into every agent session.
# Centralized source: .ai/harness/hooks/session-start.sh
# Auto-generated by codebase-harness. DO NOT EDIT directly.
#
# Output budget: ≤4 KiB total. Truncates aggressively.
# Exit 0 always — non-blocking.

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-${GEMINI_PROJECT_DIR:-${PWD}}}"
HARNESS_DIR="${PROJECT_DIR}/.ai/harness"
RUNTIME_DIR="${PROJECT_DIR}/.ai/runtime"
MEMORY_DIR="${PROJECT_DIR}/.ai/memory"

# Silent skip if no harness
[ -d "${HARNESS_DIR}" ] || exit 0

echo "=== HARNESS ANCHOR CONTEXT (auto-loaded by SessionStart) ==="
echo "Harness: ${HARNESS_DIR#${PROJECT_DIR}/}"
echo "Read these files BEFORE any content tool call."
echo

# 1. Recall bundle (highest signal-density when present)
if [ -f "${RUNTIME_DIR}/second-brain/recall-bundle.md" ]; then
  echo "## Recall Bundle"
  head -c 1500 "${RUNTIME_DIR}/second-brain/recall-bundle.md" 2>/dev/null || true
  echo
fi

# 2. DDD project identity — first 40 lines (task-startup index lives at top)
if [ -f "${HARNESS_DIR}/ddd-project.md" ]; then
  echo "## Project Identity (.ai/harness/ddd-project.md)"
  head -n 85 "${HARNESS_DIR}/ddd-project.md" 2>/dev/null || true
  echo
fi

# 3. Domain vocabulary pointer
if [ -f "${HARNESS_DIR}/ddd-ubiquitous-language.md" ]; then
  echo "## Domain Vocabulary (.ai/harness/ddd-ubiquitous-language.md)"
  echo "Use ONLY domain terms from this file. Prohibited synonyms:"
  grep -i "NEVER USE\|prohibited" "${HARNESS_DIR}/ddd-ubiquitous-language.md" 2>/dev/null | head -6 || true
  echo
fi

# 4. Critical and high lessons
if [ -f "${MEMORY_DIR}/lessons-learned.json" ] && command -v jq >/dev/null 2>&1; then
  echo "## Critical Lessons (.ai/memory/lessons-learned.json)"
  jq -r '
    (if type == "array" then . else (.entries // .lessons // []) end) |
    map(select((.severity // "") | test("critical|high"; "i"))) |
    .[0:3] |
    map("- \(.id // "?"): \(.summary // .lesson // "?")")
    | .[]
  ' "${MEMORY_DIR}/lessons-learned.json" 2>/dev/null || echo "  (no critical lessons yet)"
  echo
fi

# 5. Health report if previous session left gaps
if [ -f "${PROJECT_DIR}/.ai/harness-health-report.md" ]; then
  echo "## Pending Health Report"
  head -n 12 "${PROJECT_DIR}/.ai/harness-health-report.md" 2>/dev/null || true
  echo
fi

# 6. Anchor contract
cat <<'CONTRACT'
## Anchor Contract (MUST OBEY before any content tool call)

1. Read `.ai/harness/ddd-project.md` in full
2. Read `.ai/harness/ddd-ubiquitous-language.md` in full
3. Check `.ai/memory/lessons-learned.json` for entries scoped to your task files
4. Use ONLY domain terms from the ubiquitous language
5. For on-call work: follow `.ai/harness/rules/domain/on-call-incident-workflow.md`
6. At session-end: update lessons-learned.json with new discoveries

Skipping anchor context = working without the map.
CONTRACT

echo "=== END ANCHOR CONTEXT ============================================"
