---
description: Second Brain llm-wiki protocol — governs dual-path memory, recall zones, and active handoff lifecycle when a vault is present.
globs: ["**/*"]
alwaysApply: false
---
<!-- Centralized rule: .ai/harness/rules/governance/llm-wiki-protocol.md -->
<!-- Auto-generated by codebase-harness. Edit the centralized rule, not this wrapper. -->

> **SOURCE**: `.ai/harness/rules/governance/llm-wiki-protocol.md` — edit THAT file, not this wrapper.

---
name: llm-wiki-protocol
description: Second Brain llm-wiki protocol — governs dual-path memory, recall zones, and active handoff lifecycle when a vault is present.
type: governance
stack: generic
globs: ["**/*"]
---
<!-- Auto-generated by codebase-harness when a valid Second Brain vault is detected. -->

# llm-wiki Protocol

This rule applies when `$SECOND_BRAIN_PATH` or `$SECOND_BRAIN_VAULT_LOCAL` points to a vault with `llm-wiki/_index.md`.

## Read Protocol

Before substantive work, read only the task-relevant slice:

1. `llm-wiki/memory/` — standing behavioral directives, user preferences, retrieval policy
2. `llm-wiki/active/handoffs/` — continuation notes with first action
3. `llm-wiki/active/tasks/` — active task state for resumed work
4. `llm-wiki/context/repos/` — repo-specific durable context
5. `llm-wiki/learnings/gotchas/` — tool and workflow pitfalls relevant to this task

If the vault is absent, skip these reads. Do not invent vault paths.

## Write Protocol

Durable insights are dual-path:

1. Write the markdown companion first in the correct `llm-wiki/` zone.
2. Then add or update `.ai/memory/lessons-learned.json`.
3. Cross-reference both ways when practical.

## Zone Routing

| Zone | Use For |
|------|---------|
| `llm-wiki/memory/` | Standing behavioral directives and user preferences |
| `llm-wiki/learnings/lessons/` | Session lessons with future reuse value |
| `llm-wiki/learnings/feedback/` | Direct user corrections about agent behavior |
| `llm-wiki/learnings/gotchas/` | Tool, runtime, or workflow pitfalls |
| `llm-wiki/patterns/` | Recurring validated patterns |
| `llm-wiki/context/repos/` | Repo-specific durable context |
| `llm-wiki/context/tools/` | Tool semantics and local command behavior |
| `llm-wiki/context/machine/` | Machine/runtime metadata |
| `llm-wiki/episodes/` | Session summaries with durable narrative value |
| `llm-wiki/active/tasks/` | Ephemeral in-progress task state |
| `llm-wiki/active/handoffs/` | Short continuation notes for the next session |

## Active Note Lifecycle

- Handoffs: ≤200 words, include `first_action`
- Active task notes: include `review_after`
- Expired notes: archive or prune during reflection
- Do not leave active notes as permanent memory
