---
description: Engineering log repository structure — canonical directory layout and file placement rules.
globs: ["**/*"]
alwaysApply: false
---
<!-- Centralized rule: .ai/harness/rules/structure/repository-structure.md -->
<!-- Auto-generated by codebase-harness. DO NOT EDIT directly. -->
<!-- Auto-generated by codebase-harness -->
<!-- Refreshed by session-start hook. Source: .ai/harness/rules/structure/repository-structure.md -->

# Repository Structure

## Top-Level Layout

```
engineering-log/
├── AGENTS.md           # Codex/universal root file (thin wrapper → .ai/harness/AGENTS.md)
├── CLAUDE.md           # Claude Code root file (thin wrapper → .ai/harness/AGENTS.md)
├── GEMINI.md           # Gemini CLI root file (thin wrapper → .ai/harness/AGENTS.md)
├── README.md
│
├── log/                # Engineering log entries (primary content)
│   └── employer/
│       ├── eneco/      # Eneco Trade Platform work
│       │   ├── 00_incident_sre/     # Alert analysis, runbooks
│       │   ├── 01_trade_platform_team/  # Team-scoped docs
│       │   ├── 02_on_call_shift/    # On-call incident logs (one dir per incident)
│       │   └── {topic}/             # Ad-hoc topic dirs
│       └── other/      # Other employer notes
│
├── engineering/        # Technical design documents and proposals
├── docs/guides/        # How-to guides (analysis protocols, visual aids)
├── scratchpad/         # Working notes and drafts
│
└── .ai/
    ├── harness/        # Codebase harness (SINGLE SOURCE OF TRUTH for rules/DDD/skills)
    │   ├── AGENTS.md   # Centralized shared instructions
    │   ├── ddd-project.md
    │   ├── ddd-ubiquitous-language.md
    │   ├── rules/      # Centralized rules
    │   ├── skills/     # Centralized skills
    │   ├── hooks/      # Hook scripts
    │   └── specs/      # Log entry templates and specs
    ├── memory/
    │   └── lessons-learned.json
    ├── tasks/          # Task workspaces (.ai/tasks/{task_id}_{slug}/)
    └── runtime/        # Runtime state (recall bundle, current-task.json)
```

## Placement Rules

- **On-call logs**: `log/employer/eneco/02_on_call_shift/{YYYY_MM_DD}_{slug}/`
- **Alert incident logs**: `log/employer/eneco/00_incident_sre/{slug}/`
- **Task workspaces**: `.ai/tasks/{YYYY-MM-DD-NNN}_{slug}/`
- **Draft notes**: `scratchpad/` (no structure requirement)
- **Persistent memory**: `.ai/memory/lessons-learned.json` ONLY

## File Naming

- Markdown files: `kebab-case.md` (lowercase, hyphens)
- Directories: `snake_case` or `{NNN}_{slug}` pattern
- Task slugs: `[a-z0-9]+(-[a-z0-9]+)*`

## Harness Files

`.ai/harness/` is the single source of truth. Do NOT edit generated wrappers directly.
Generated wrappers: `.claude/rules/`, `.cursor/rules/`, `.gemini/skills/`
