#!/usr/bin/env bash
# validate-harness-completeness.sh — Final comprehensive harness completeness check.
# Validates EVERY file and directory the harness MUST produce.
# Run this AFTER the harness skill completes to ensure zero gaps.
#
# Usage:
#   ./validate-harness-completeness.sh [PROJECT_DIR]
#
# Exit codes:
#   0 — harness is complete
#   1 — harness has gaps
#   2 — no harness found
set -euo pipefail

_git_root() { git -C "${1:-.}" rev-parse --show-toplevel 2>/dev/null || echo "${1:-.}"; }
usage() {
  cat <<'EOF'
Usage: validate-harness-completeness.sh [PROJECT_DIR]

Validate that a generated harness is complete and that derived surfaces
still match centralized truth.
EOF
}
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi
PROJECT_DIR="${1:-${CLAUDE_PROJECT_DIR:-$(_git_root "$(pwd)")}}"
if [[ ! -d "$PROJECT_DIR" ]]; then
  echo "ERROR: directory not found: $PROJECT_DIR" >&2; exit 1
fi

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m'
  CYAN='\033[0;36m' BOLD='\033[1m' RESET='\033[0m'
else
  RED='' GREEN='' YELLOW='' CYAN='' BOLD='' RESET=''
fi

PASS=0; FAIL=0; WARN=0
REQUIRED_GOVERNANCE_RULES=(
  memory-freshness.md
  rules-codebase-sync.md
  ddd-freshness.md
  root-files-freshness.md
  specs-driven.md
  anchor-context-startup.md
  harness-self-improvement.md
  anti-slop-gate.md
  adversarial-dispatch-discipline.md
  actionable-artifact-gate.md
)
OPTIONAL_GOVERNANCE_RULES=(
  llm-wiki-protocol.md
)
_pass() { printf '  %sPASS%s  %s\n' "$GREEN" "$RESET" "$1"; PASS=$((PASS+1)); }
_fail() { printf '  %sFAIL%s  %s — %s\n' "$RED" "$RESET" "$1" "$2"; FAIL=$((FAIL+1)); }
_warn() { printf '  %sWARN%s  %s — %s\n' "$YELLOW" "$RESET" "$1" "$2"; WARN=$((WARN+1)); }
_head() { printf '\n%s%s%s%s\n' "$BOLD" "$CYAN" "$1" "$RESET"; }
_extract_marker_path() {
  local file="$1"
  local prefix="$2"
  python3 - "$file" "$prefix" <<'PY'
import sys

path, prefix = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as fh:
    for line in fh:
        if prefix in line:
            value = line.split(prefix, 1)[1].strip()
            if "-->" in value:
                value = value.split("-->", 1)[0].strip()
            print(value)
            break
PY
}
_compare_markdown_wrapper_body() {
  local central="$1"
  local wrapper="$2"
  python3 - "$central" "$wrapper" <<'PY'
import sys

central_path, wrapper_path = sys.argv[1], sys.argv[2]

def read_lines(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read().splitlines()

def strip_outer_frontmatter(lines):
    if lines and lines[0].strip() == "---":
        i = 1
        while i < len(lines) and lines[i].strip() != "---":
            i += 1
        if i < len(lines):
            return lines[i + 1 :]
    return lines

def normalize_plain(lines):
    out = []
    for line in lines:
        if line.startswith("<!-- Auto-generated by codebase-harness"):
            continue
        out.append(line.rstrip())
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out).strip()

def normalize_wrapper(lines):
    lines = strip_outer_frontmatter(lines)
    out = []
    leading = True
    for line in lines:
        stripped = line.strip()
        if line.startswith("<!-- Centralized ") or line.startswith("<!-- Auto-generated by codebase-harness"):
            continue
        if line.startswith("# Centralized source:"):
            continue
        if line.startswith("> **SOURCE**:"):
            continue
        if leading and not stripped:
            continue
        leading = False
        out.append(line.rstrip())
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out).strip()

central = normalize_plain(read_lines(central_path))
wrapper = normalize_wrapper(read_lines(wrapper_path))
sys.exit(0 if central == wrapper else 1)
PY
}
_check_marker_equals() {
  local label="$1"
  local wrapper="$2"
  local prefix="$3"
  local expected="$4"
  local marker
  marker="$(_extract_marker_path "$wrapper" "$prefix")"
  if [[ -z "$marker" ]]; then
    _fail "$label" "missing source marker ($prefix)"
    return
  fi
  if [[ "$marker" == "$expected" ]]; then
    _pass "$label marker → $expected"
  else
    _fail "$label" "marker points to '$marker' (expected '$expected')"
  fi
  if [[ -f "$PROJECT_DIR/$marker" ]]; then
    _pass "$label source exists"
  else
    _fail "$label source" "referenced source '$marker' missing"
  fi
}
_check_markdown_wrapper() {
  local label="$1"
  local central_rel="$2"
  local wrapper_rel="$3"
  local prefix="$4"

  if [[ ! -f "$PROJECT_DIR/$wrapper_rel" ]]; then
    _fail "$label" "missing wrapper $wrapper_rel"
    return
  fi

  _check_marker_equals "$label" "$PROJECT_DIR/$wrapper_rel" "$prefix" "$central_rel"
  if _compare_markdown_wrapper_body "$PROJECT_DIR/$central_rel" "$PROJECT_DIR/$wrapper_rel"; then
    _pass "$label body parity"
  else
    _fail "$label body" "wrapper content drift vs $central_rel"
  fi
}
_check_resolved_paths() {
  local scan_root="$1"
  python3 - "$PROJECT_DIR" "$scan_root" <<'PY'
import os
import re
import sys

project_dir, scan_root = sys.argv[1], sys.argv[2]
scan_path = os.path.join(project_dir, scan_root)
pattern = re.compile(r'(?<![\w/.-])(?:AGENTS\.md|CLAUDE\.md|GEMINI\.md|\.ai(?:/[A-Za-z0-9._@{}-]+)+|\.claude(?:/[A-Za-z0-9._@{}-]+)+|\.cursor(?:/[A-Za-z0-9._@{}-]+)+|\.gemini(?:/[A-Za-z0-9._@{}-]+)+|\.codex(?:/[A-Za-z0-9._@{}-]+)+)')

bad = []
targets = []
if os.path.isfile(scan_path):
    targets = [scan_path]
else:
    for root, _, files in os.walk(scan_path):
        for name in files:
            if name.endswith(".md"):
                targets.append(os.path.join(root, name))

for path in targets:
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    for line in lines:
      optional = any(marker in line.lower() for marker in [
          "if present",
          "if it exists",
          "when configured",
          "if second brain",
          "if `$second_brain_path",
          "if $second_brain_path",
          "if task-local lessons exist",
          "when `$second_brain_path",
          "when $second_brain_path",
          "when neither `$second_brain_path",
          "optional",
          "if present",
      ])
      for match in sorted(set(pattern.findall(line))):
        if any(ch in match for ch in "{}*"):
            continue
        target = os.path.join(project_dir, match)
        if not os.path.exists(target):
            if optional:
                continue
            bad.append((os.path.relpath(path, project_dir), match))

for rel, target in bad:
    print(f"{rel}|{target}")
PY
}

if [[ ! -d "$PROJECT_DIR/.ai/harness" ]]; then
  printf '%sNo harness found at %s/.ai/harness/%s\n' "$YELLOW" "$PROJECT_DIR" "$RESET"
  exit 2
fi

printf '%s=== Harness Completeness Validation ===%s\n' "$BOLD" "$RESET"
printf 'Project: %s\n' "$PROJECT_DIR"

# ── 1. Root Context Files ────────────────────────────────────────────
_head "1. Root Context Files"
for f in AGENTS.md CLAUDE.md GEMINI.md; do
  if [[ -f "$PROJECT_DIR/$f" ]]; then
    lines=$(wc -l < "$PROJECT_DIR/$f" | tr -d ' ')
    _pass "$f ($lines lines)"
    if grep -q '<!-- Auto-generated by codebase-harness -->' "$PROJECT_DIR/$f" 2>/dev/null; then
      _pass "$f auto-generated marker"
    else
      _warn "$f" "missing auto-generated marker"
    fi
    if grep -q '.ai/harness/AGENTS.md' "$PROJECT_DIR/$f" 2>/dev/null; then
      _pass "$f references centralized AGENTS"
    else
      _fail "$f" "does not point readers at .ai/harness/AGENTS.md"
    fi
  else
    _fail "$f" "missing at project root"
  fi
done

# ── 2. Centralized Harness Structure ─────────────────────────────────
_head "2. Centralized Harness Structure"
for d in rules skills commands hooks agents specs context; do
  if [[ -d "$PROJECT_DIR/.ai/harness/$d" ]]; then
    _pass ".ai/harness/$d/"
  else
    _fail ".ai/harness/$d/" "directory missing"
  fi
done

# ── 3. DDD Files (Mandatory) ─────────────────────────────────────────
_head "3. DDD Knowledge Files"
if [[ -f "$PROJECT_DIR/.ai/harness/ddd-ubiquitous-language.md" ]]; then
  _pass "ddd-ubiquitous-language.md"
  # Check it has content (not just template placeholders)
  if grep -q '{{' "$PROJECT_DIR/.ai/harness/ddd-ubiquitous-language.md" 2>/dev/null; then
    _warn "ddd-ubiquitous-language.md" "contains unfilled {{placeholders}}"
  fi
else
  _fail "ddd-ubiquitous-language.md" "MISSING — domain vocabulary not captured"
fi

if [[ -f "$PROJECT_DIR/.ai/harness/ddd-project.md" ]]; then
  _pass "ddd-project.md"
  if grep -q '{{' "$PROJECT_DIR/.ai/harness/ddd-project.md" 2>/dev/null; then
    _warn "ddd-project.md" "contains unfilled {{placeholders}}"
  fi
else
  _fail "ddd-project.md" "MISSING — project intelligence not captured"
fi

# ── 3b. Context Intelligence (Mandatory) ─────────────────────────────
_head "3b. Context Intelligence"
for f in pattern-map.md recent-changes.md gotchas-limitations.md; do
  if [[ -f "$PROJECT_DIR/.ai/harness/context/$f" ]]; then
    _pass "context/$f"
  else
    _fail "context/$f" "MISSING - harness lacks required codebase intelligence surface"
  fi
done

# ── 4. Governance Rules (Mandatory + conditional) ─────────────────────
_head "4. Governance Rules"
for r in "${REQUIRED_GOVERNANCE_RULES[@]}"; do
  if [[ -f "$PROJECT_DIR/.ai/harness/rules/governance/$r" ]]; then
    _pass "governance/$r"
  else
    _fail "governance/$r" "mandatory governance rule missing"
  fi
done
for r in "${OPTIONAL_GOVERNANCE_RULES[@]}"; do
  if [[ -f "$PROJECT_DIR/.ai/harness/rules/governance/$r" ]]; then
    _pass "governance/$r"
  else
    _warn "governance/$r" "optional unless a Second Brain vault is configured"
  fi
done

# ── 5. Rules Index ───────────────────────────────────────────────────
_head "5. Rules Index"
if [[ -f "$PROJECT_DIR/.ai/harness/rules/RULES.md" ]]; then
  _pass "RULES.md index"
else
  _fail "RULES.md" "rules index missing"
fi

# ── 6. Repository Memory ─────────────────────────────────────────────
_head "6. Persistent Memory"
if [[ -d "$PROJECT_DIR/.ai/memory" ]]; then
  if [[ -f "$PROJECT_DIR/.ai/memory/lessons-learned.json" ]]; then
    if python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$PROJECT_DIR/.ai/memory/lessons-learned.json" 2>/dev/null; then
      _pass "lessons-learned.json (valid JSON)"
    else
      _fail "lessons-learned.json" "exists but invalid JSON"
    fi
  else
    _fail "lessons-learned.json" "missing"
  fi
else
  _fail ".ai/memory/" "directory missing"
fi

# Centralized shared instructions
if [[ -f "$PROJECT_DIR/.ai/harness/AGENTS.md" ]]; then
  _pass ".ai/harness/AGENTS.md (centralized instructions)"
else
  _fail ".ai/harness/AGENTS.md" "centralized instructions missing"
fi

# ── 7. Claude Code Configuration ─────────────────────────────────────
_head "7. Claude Code"
if [[ -d "$PROJECT_DIR/.claude/rules" ]]; then
  count=$(find "$PROJECT_DIR/.claude/rules" -name '*.md' -type f 2>/dev/null | wc -l | tr -d ' ')
  _pass ".claude/rules/ ($count rules)"
else
  _fail ".claude/rules/" "directory missing"
fi

if [[ -f "$PROJECT_DIR/.claude/settings.json" ]]; then
  if python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$PROJECT_DIR/.claude/settings.json" 2>/dev/null; then
    if python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert 'hooks' in d" "$PROJECT_DIR/.claude/settings.json" 2>/dev/null; then
      _pass ".claude/settings.json (valid JSON, hooks configured)"
    else
      _warn ".claude/settings.json" "valid JSON but no hooks configured"
    fi
  else
    _fail ".claude/settings.json" "invalid JSON"
  fi
else
  _warn ".claude/settings.json" "missing (hooks not wired)"
fi

# ── 8. Cursor Configuration ──────────────────────────────────────────
_head "8. Cursor"
if [[ -d "$PROJECT_DIR/.cursor/rules" ]]; then
  count=$(find "$PROJECT_DIR/.cursor/rules" -name '*.mdc' -type f 2>/dev/null | wc -l | tr -d ' ')
  _pass ".cursor/rules/ ($count rules)"
else
  _fail ".cursor/rules/" "directory missing"
fi

# ── 9. Gemini CLI Configuration ──────────────────────────────────────
_head "9. Gemini CLI"
if [[ -d "$PROJECT_DIR/.gemini" ]]; then
  _pass ".gemini/ directory"
else
  _warn ".gemini/" "directory missing"
fi

# ── 10. Codex CLI Configuration ──────────────────────────────────────
_head "10. Codex CLI"
if [[ -d "$PROJECT_DIR/.codex" ]]; then
  _pass ".codex/ directory"
else
  _warn ".codex/" "directory missing"
fi

# ── 11. Hooks ─────────────────────────────────────────────────────────
_head "11. Hook Scripts"
# claim-task-id.sh is the atomic, parallel-safe task_id allocator that ships alongside
# the task-workspace-guard hook (per-session sentinel model). Validated here as a generated
# harness artifact in the same .ai/harness/hooks/ surface as the guard it pairs with.
for h in post-edit.sh task-workspace-guard.sh claim-task-id.sh refresh-repo-structure.sh session-end.sh; do
  if [[ -f "$PROJECT_DIR/.ai/harness/hooks/$h" ]]; then
    if [[ -x "$PROJECT_DIR/.ai/harness/hooks/$h" ]]; then
      _pass "hooks/$h (executable)"
    else
      _fail "hooks/$h" "exists but NOT executable"
    fi
  else
    _warn "hooks/$h" "not generated"
  fi
done

# ── 12. SKILLs (≥1 for non-trivial repos) ────────────────────────────
_head "12. SKILLs"
skill_count=$(find "$PROJECT_DIR/.ai/harness/skills" -name '*.md' -type f 2>/dev/null | wc -l | tr -d ' ')
if [[ "$skill_count" -gt 0 ]]; then
  _pass "SKILLs generated: $skill_count"
  # Verify each SKILL has required fields
  while IFS= read -r -d '' skill; do
    name=$(basename "$skill" .md)
    if grep -q 'trigger' "$skill" 2>/dev/null && grep -q 'Steps\|steps' "$skill" 2>/dev/null; then
      _pass "SKILL $name has trigger + steps"
    else
      _warn "SKILL $name" "missing trigger or steps section"
    fi
  done < <(find "$PROJECT_DIR/.ai/harness/skills" -name '*.md' -type f -print0 2>/dev/null)
else
  _warn "SKILLs" "none generated (expected ≥1 for non-trivial repos)"
fi

# ── 13. Agents ────────────────────────────────────────────────────────
_head "13. Agents"
agent_count=$(find "$PROJECT_DIR/.ai/harness/agents" -name '*.md' -type f 2>/dev/null | wc -l | tr -d ' ')
printf '  Agents generated: %s\n' "$agent_count"

# ── 14. Rule Wrapper Parity ──────────────────────────────────────────
_head "14. Rule Wrapper Parity"
while IFS= read -r -d '' central; do
  rel="${central#"$PROJECT_DIR"/}"
  base=$(basename "$central" .md)
  ns=$(basename "$(dirname "$central")")
  _check_markdown_wrapper "Claude rule ${ns}/${base}" "$rel" ".claude/rules/${ns}/${base}.md" "Centralized rule:"
  _check_markdown_wrapper "Cursor rule ${ns}/${base}" "$rel" ".cursor/rules/${ns}-${base}.mdc" "Centralized rule:"
done < <(find "$PROJECT_DIR/.ai/harness/rules" -mindepth 2 -maxdepth 2 -name '*.md' -type f ! -name 'RULES.md' -print0 2>/dev/null)

while IFS= read -r -d '' wrapper; do
  rel="${wrapper#"$PROJECT_DIR"/}"
  marker="$(_extract_marker_path "$wrapper" "Centralized rule:")"
  if [[ -n "$marker" && -f "$PROJECT_DIR/$marker" ]]; then
    _pass "Live source for $rel"
  else
    _fail "$rel" "stale or missing centralized rule source"
  fi
done < <(find "$PROJECT_DIR/.claude/rules" "$PROJECT_DIR/.cursor/rules" -type f \( -name '*.md' -o -name '*.mdc' \) -print0 2>/dev/null)

# ── 15. Skill Wrapper Parity ─────────────────────────────────────────
_head "15. Skill Wrapper Parity"
while IFS= read -r -d '' central; do
  rel="${central#"$PROJECT_DIR"/}"
  base=$(basename "$central" .md)
  _check_markdown_wrapper "Claude skill $base" "$rel" ".claude/skills/${base}/SKILL.md" "Centralized skill:"
  _check_markdown_wrapper "Cursor skill $base" "$rel" ".cursor/skills/${base}/SKILL.md" "Centralized skill:"
  _check_markdown_wrapper "Gemini skill $base" "$rel" ".gemini/skills/${base}/SKILL.md" "Centralized skill:"
  _check_markdown_wrapper "Codex skill $base" "$rel" ".codex/skills/${base}/SKILL.md" "Centralized skill:"
done < <(find "$PROJECT_DIR/.ai/harness/skills" -maxdepth 1 -name '*.md' -type f -print0 2>/dev/null)

for dir in .claude/skills .cursor/skills .gemini/skills .codex/skills; do
  [[ -d "$PROJECT_DIR/$dir" ]] || continue
  while IFS= read -r -d '' wrapper; do
    rel="${wrapper#"$PROJECT_DIR"/}"
    marker="$(_extract_marker_path "$wrapper" "Centralized skill:")"
    agent_marker="$(_extract_marker_path "$wrapper" "Centralized agent:")"
    source_marker="$(_extract_marker_path "$wrapper" "Centralized source:")"
    if [[ -n "$marker" && -f "$PROJECT_DIR/$marker" ]]; then
      _pass "Live source for $rel"
    elif [[ "$agent_marker" == .ai/harness/agents/* && -f "$PROJECT_DIR/$agent_marker" ]]; then
      _pass "Live agent source for $rel"
    elif [[ "$source_marker" == .ai/harness/agents/* && -f "$PROJECT_DIR/$source_marker" ]]; then
      _pass "Live agent source for $rel"
    else
      _fail "$rel" "stale or missing centralized skill source"
    fi
  done < <(find "$PROJECT_DIR/$dir" -name 'SKILL.md' -type f -print0 2>/dev/null)
done

# ── 16. Agent Wrapper Parity ─────────────────────────────────────────
_head "16. Agent Wrapper Parity"
while IFS= read -r -d '' central; do
  rel="${central#"$PROJECT_DIR"/}"
  base=$(basename "$central" .md)
  _check_markdown_wrapper "Claude agent $base" "$rel" ".claude/agents/${base}.md" "Centralized agent:"
  if [[ -f "$PROJECT_DIR/.gemini/skills/${base}/SKILL.md" ]]; then
    agent_marker="$(_extract_marker_path "$PROJECT_DIR/.gemini/skills/${base}/SKILL.md" "Centralized agent:")"
    skill_marker="$(_extract_marker_path "$PROJECT_DIR/.gemini/skills/${base}/SKILL.md" "Centralized skill:")"
    source_marker="$(_extract_marker_path "$PROJECT_DIR/.gemini/skills/${base}/SKILL.md" "Centralized source:")"
    if [[ "$agent_marker" == "$rel" || "$skill_marker" == "$rel" || "$source_marker" == "$rel" ]]; then
      _pass "Gemini agent $base marker → $rel"
      if _compare_markdown_wrapper_body "$PROJECT_DIR/$rel" "$PROJECT_DIR/.gemini/skills/${base}/SKILL.md"; then
        _pass "Gemini agent $base body parity"
      else
        _fail "Gemini agent $base body" "wrapper content drift vs $rel"
      fi
    elif [[ "$skill_marker" == ".ai/harness/skills/${base}.md" ]]; then
      _pass "Gemini agent $base skipped (name reserved by Gemini skill wrapper)"
    else
      _fail "Gemini agent $base" "missing or incorrect centralized marker"
    fi
  else
    _pass "Gemini agent $base skipped (no dedicated Gemini agent wrapper)"
  fi
  if [[ -f "$PROJECT_DIR/.codex/agents/${base}.toml" ]]; then
    codex_marker="$(_extract_marker_path "$PROJECT_DIR/.codex/agents/${base}.toml" "Centralized source:")"
    [[ -n "$codex_marker" ]] || codex_marker="$(_extract_marker_path "$PROJECT_DIR/.codex/agents/${base}.toml" "SOURCE:")"
    if [[ "$codex_marker" == "$rel"* ]]; then
      _pass "Codex agent $base marker → $rel"
    elif [[ -n "$codex_marker" ]]; then
      _fail "Codex agent $base" "marker points to '$codex_marker' (expected '$rel')"
    else
      _fail "Codex agent $base" "missing source marker (Centralized source:)"
    fi
  else
    _fail "Codex agent $base" "missing wrapper .codex/agents/${base}.toml"
  fi
done < <(find "$PROJECT_DIR/.ai/harness/agents" -maxdepth 1 -name '*.md' -type f -print0 2>/dev/null)

# ── 17. Local Path Reference Integrity ───────────────────────────────
_head "17. Local Path Reference Integrity"
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  file_rel="${line%%|*}"
  target="${line#*|}"
  _fail "$file_rel" "references missing path $target"
done < <(_check_resolved_paths ".ai/harness")
for root_file in AGENTS.md CLAUDE.md GEMINI.md; do
  [[ -f "$PROJECT_DIR/$root_file" ]] || continue
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    file_rel="${line%%|*}"
    target="${line#*|}"
    _fail "$file_rel" "references missing path $target"
  done < <(_check_resolved_paths "$root_file")
done

# ── Summary ──────────────────────────────────────────────────────────
printf '\n%s=== Summary ===%s\n' "$BOLD" "$RESET"
printf '  Passed:   %s%d%s\n' "$GREEN" "$PASS" "$RESET"
printf '  Failed:   %s%d%s\n' "$RED" "$FAIL" "$RESET"
printf '  Warnings: %s%d%s\n' "$YELLOW" "$WARN" "$RESET"

if [[ "$FAIL" -gt 0 ]]; then
  printf '\n%s%sHARNESS INCOMPLETE%s — %d mandatory check(s) failed.\n' "$RED" "$BOLD" "$RESET" "$FAIL"
  exit 1
fi

if [[ "$WARN" -gt 0 ]]; then
  printf '\n%s%sHARNESS COMPLETE (with warnings)%s — %d non-critical item(s).\n' "$YELLOW" "$BOLD" "$RESET" "$WARN"
else
  printf '\n%s%sHARNESS COMPLETE%s — all checks passed.\n' "$GREEN" "$BOLD" "$RESET"
fi
exit 0
